DROP SCHEMA IF EXISTS ubd_20222 CASCADE;

CREATE SCHEMA ubd_20222 AUTHORIZATION postgres;

GRANT ALL ON SCHEMA ubd_20222 TO postgres;

SET search_path TO ubd_20222;

BEGIN WORK;

SET TRANSACTION READ WRITE;

SET datestyle = DMY;

CREATE TABLE OWNER (
	id_owner SMALLINT NOT NULL,
	name_owner VARCHAR(255) NOT NULL,
	phone INT NOT NULL,
	address VARCHAR(255),
	CONSTRAINT PK_OWNER PRIMARY KEY (id_owner));

CREATE TABLE DOG (
	id_dog SMALLINT NOT NULL,
	name_dog VARCHAR(255) NOT NULL,
	breed VARCHAR(255) NOT NULL,
	birth DATE NOT NULL,
	death DATE,
	sex VARCHAR(255) NOT NULL,
	color VARCHAR(255) NOT NULL,
	fur VARCHAR (255) NOT NULL,
	id_owner SMALLINT NOT NULL,
	num_vaccines SMALLINT DEFAULT 0,
	CONSTRAINT PK_DOG PRIMARY KEY(id_dog),
	CONSTRAINT FK_OWNER_DOG FOREIGN KEY (id_owner) REFERENCES OWNER(id_owner) ON UPDATE CASCADE,
	CONSTRAINT sex CHECK (sex IN ('M','F')),
	CONSTRAINT fur CHECK (fur IN ('Short', 'Medium', 'Long')),
   CONSTRAINT CHECK_DEATH CHECK (death IS NULL OR birth < death));

CREATE TABLE DRUG (
	id_drug SMALLINT NOT NULL,
	name_drug VARCHAR(255) UNIQUE NOT NULL,
	format VARCHAR(255) NOT NULL,
	type VARCHAR(255) NOT NULL,
	CONSTRAINT PK_DRUG PRIMARY KEY(id_drug));
	
CREATE TABLE VACCINE (
	id_vaccine SMALLINT NOT NULL,
	name_vaccine VARCHAR(255) UNIQUE NOT NULL,
	periodicity SMALLINT DEFAULT NULL,
	pharma VARCHAR(255) DEFAULT NULL,
	CONSTRAINT PK_VACCINE PRIMARY KEY (id_vaccine),
	CONSTRAINT PERIODICITY_NO_ZERO CHECK (periodicity IS NULL OR periodicity > 0));

CREATE TABLE TEST(
	id_test SMALLINT NOT NULL,
	type_test VARCHAR(255) NOT NULL,
	CONSTRAINT PK_TEST PRIMARY KEY(id_test));

CREATE TABLE VISIT(
	id_visit SERIAL PRIMARY KEY,
	id_dog SMALLINT NOT NULL,
	date DATE NOT NULL,
	reason VARCHAR(255) NOT NULL,
	id_veterinary SMALLINT NOT NULL,
	comments VARCHAR(255),
	CONSTRAINT FK_DOG_VISIT FOREIGN KEY(id_dog) REFERENCES DOG(id_dog) ON UPDATE CASCADE,
	CONSTRAINT reason CHECK (reason IN ('vaccination', 'follow-up', 'illness')));


CREATE TABLE PRESCRIPTION (
	id_visit SMALLINT NOT NULL,
	id_drug SMALLINT NOT NULL,
	dose SMALLINT NOT NULL,
	duration SMALLINT NOT NULL CHECK( duration >= 0),
	CONSTRAINT PK_PRESCRIPTION PRIMARY KEY(id_visit, id_drug),
	CONSTRAINT FK_VISIT_PRESCRIPTION FOREIGN KEY (id_visit) REFERENCES VISIT(id_visit) ON UPDATE CASCADE,
	CONSTRAINT FK_DRUG_PRESCRIPTION FOREIGN KEY(id_drug) REFERENCES DRUG(id_drug) ON UPDATE CASCADE,
	CONSTRAINT dose CHECK (dose IN (1, 2, 3)));

CREATE TABLE VACCINATION (
	id_visit SMALLINT NOT NULL,
	id_vaccine SMALLINT NOT NULL,
	CONSTRAINT PK_VACCINATION PRIMARY KEY(id_visit, id_vaccine),
	CONSTRAINT FK_VISIT_VACCINATION FOREIGN KEY(id_visit) REFERENCES VISIT(id_visit) ON UPDATE CASCADE,
	CONSTRAINT FK_VACCINE_VACCINATION FOREIGN KEY(id_vaccine) REFERENCES VACCINE(id_vaccine) ON UPDATE CASCADE);

CREATE TABLE DOG_TEST (
	id_test SMALLINT NOT NULL,
	id_visit SMALLINT NOT NULL,
	CONSTRAINT PK_DOG_TEST PRIMARY KEY(id_test, id_visit),
	CONSTRAINT FK_TEST_DOG_TEST FOREIGN KEY(id_test) REFERENCES TEST(id_test) ON UPDATE CASCADE,
	CONSTRAINT FK_VISIT_DOG_TEST FOREIGN KEY(id_visit) REFERENCES VISIT(id_visit) ON UPDATE CASCADE);
	
CREATE TABLE REPORT_DOG (
	id_dog SMALLINT,
	name_dog VARCHAR(255),
	birth DATE,
	name_owner VARCHAR(255),
	phone INTEGER,
	num_visits SMALLINT,
	num_dif_vaccines SMALLINT,
	date_last_vaccine date,
	num_drugs SMALLINT,
	num_tests SMALLINT,
	CONSTRAINT PK_REPORT_DOG PRIMARY KEY(id_dog));

CREATE TYPE REPORT_DOG_TYPE AS (
	t_id_dog SMALLINT,
	t_name_dog VARCHAR(255),
	t_birth DATE,
	t_name_owner VARCHAR(255),
	t_phone INTEGER,
	t_num_visits SMALLINT,
	t_num_dif_vaccines SMALLINT,
	t_last_vaccine date,
	t_num_drugs SMALLINT,
	t_num_tests SMALLINT);
	
COMMIT;